# utils/company_map.py

# Mapping of human-readable company names to ticker symbols
# You can add / remove entries here as you like.

COMPANY_TICKER_MAP = {
    # =========================
    # 🇮🇳 Indian Large Caps
    # =========================
    "Reliance Industries": "RELIANCE.NS",
    "Tata Consultancy Services": "TCS.NS",
    "Infosys": "INFY.NS",
    "HDFC Bank": "HDFCBANK.NS",
    "ICICI Bank": "ICICIBANK.NS",
    "State Bank of India": "SBIN.NS",
    "Bharti Airtel": "BHARTIARTL.NS",
    "ITC": "ITC.NS",
    "Bajaj Finance": "BAJFINANCE.NS",
    "Larsen & Toubro": "LT.NS",
    "Asian Paints": "ASIANPAINT.NS",
    "Maruti Suzuki": "MARUTI.NS",
    "Axis Bank": "AXISBANK.NS",
    "Kotak Mahindra Bank": "KOTAKBANK.NS",
    "Sun Pharma": "SUNPHARMA.NS",
    "Hindustan Unilever": "HINDUNILVR.NS",
    "ONGC": "ONGC.NS",
    "Wipro": "WIPRO.NS",
    "Tata Motors": "TATAMOTORS.NS",
    "NTPC": "NTPC.NS",
    "Power Grid": "POWERGRID.NS",
    "Coal India": "COALINDIA.NS",
    "Adani Enterprises": "ADANIENT.NS",
    "UltraTech Cement": "ULTRACEMCO.NS",
    "Titan Company": "TITAN.NS",
    "Tata Steel": "TATASTEEL.NS",
    "JSW Steel": "JSWSTEEL.NS",
    "HCL Technologies": "HCLTECH.NS",
    "Tech Mahindra": "TECHM.NS",
    "Nestle India": "NESTLEIND.NS",

    # =========================
    # 🇺🇸 / Global Majors
    # =========================
    "Apple Inc.": "AAPL",
    "Microsoft": "MSFT",
    "Alphabet (Google) Class A": "GOOGL",
    "Amazon": "AMZN",
    "Tesla": "TSLA",
    "Meta Platforms (Facebook)": "META",
    "NVIDIA": "NVDA",
    "Berkshire Hathaway Class B": "BRK-B",
    "Visa": "V",
    "JPMorgan Chase": "JPM",
    "Procter & Gamble": "PG",
    "Exxon Mobil": "XOM",
    "PepsiCo": "PEP",
    "Mastercard": "MA",
    "Walt Disney": "DIS",
    "Netflix": "NFLX",
    "Pfizer": "PFE",
    "Intel": "INTC",
    "Nike": "NKE",
    "Coca-Cola": "KO",
    "McDonald's": "MCD",
    "Adobe": "ADBE",
    "Cisco Systems": "CSCO",
    "Salesforce": "CRM",
    "Broadcom": "AVGO",
    "Costco": "COST",
    "Advanced Micro Devices": "AMD",
    "IBM": "IBM",
    "Dell Technologies": "DELL",
    "Uber": "UBER",
    "Airbnb": "ABNB",
    "Qualcomm": "QCOM",
    "PayPal": "PYPL",
    "Shopify": "SHOP",
    "Toyota Motors": "TM",
    "Alibaba": "BABA",
    "Taiwan Semiconductor": "TSM",
}
